### ISSUE TITLE
Issues installing even with fuse present

### ISSUE THREAD

**Issue by unwitting** [Munter/fusile#17]
Love the idea of fusile, amazed by the JSConfEU demo, but having trouble installing. I have fuse installed and pretty up-to-date, and as far as I can tell I've pointed my PKG_CONFIG_PATH to its location. Any help?

```
tmp $ npm install fusile

> fuse-bindings@2.7.0 install /Users/jackpreston/tmp/node_modules/fusile/node_modules/fuse-bindings
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
gyp: Call to 'pkg-config --libs-only-L --libs-only-l fuse' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jackpreston/tmp/node_modules/fusile/node_modules/fuse-bindings
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "fusile"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! fuse-bindings@2.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fuse-bindings@2.7.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fuse-bindings package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fuse-bindings
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jackpreston/tmp/npm-debug.log
tmp $
tmp $ echo $PKG_CONFIG_PATH
/usr/local/lib/pkgconfig /usr//local/lib/pkgconfig/ /usr//local/Library/ENV/pkgconfig/fuse/
tmp $
tmp $ ls /usr//local/lib/pkgconfig/
SDL_image.pc      fontconfig.pc     fuse.pc           libavdevice.pc    libavresample.pc  libpng16.pc       libswscale.pc     libwebpdecoder.pc osxfuse.pc        sdl.pc
SDL_mixer.pc      freetype2.pc      libass.pc         libavfilter.pc    libavutil.pc      libpostproc.pc    libtiff-4.pc      libwebpdemux.pc   protobuf-lite.pc  vo-aacenc.pc
SDL_ttf.pc        fribidi.pc        libavcodec.pc     libavformat.pc    libpng.pc         libswresample.pc  libwebp.pc        libwebpmux.pc     protobuf.pc       x264.pc
```

**Comment by Munter** [comment]
Oh dear. I'm sadly just a consumer of the fuse bindings. @mafintosh do you have any insights on why this might happen?

**Comment by unwitting** [comment]
😥zero configuration _except fuse_. Thanks for the prompt reply :)

**Comment by Munter** [comment]
I'd really like to figure out how to prebuild fuse so that annoying dependency wouldn't mess up the whole experience

**Comment by unwitting** [comment]
@mafintosh if you feel like looking at this and are at jsconfeu and think it would be easier give me a shout and I'll find you with my laptop - prob easier to debug that way :)

**Comment by mafintosh** [comment]
@unwitting unfortunately i'm not at jsconf but could you try running `pkg-config --libs-only-L --libs-only-l fuse` and posting what it returns?

**Comment by unwitting** [comment]
Success - originally that was giving me the same output:

```
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
```

Had a bit more fun with the PKG_CONFIG_PATH and its format, my issue was the wrong delimiter, it's meant to be colon-separated. I'm now getting a working fusile install :)

**Comment by Munter** [comment]
\o/

Let me know when you hit the first bug ;)

**Comment by unwitting** [comment]
Oh I will :dancers:
